fileloader/main/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webapp.urls', namespace='webapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileloader/webapp/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.wav_list_view, name='list'),
    url(r'^add/$', views.wav_add_view, name='add'),
    url(r'^change/(?P<pk>[0-9]+)/$', views.wav_change_view, name='change'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.wav_delete_view, name='delete')
]

fileloader/webapp/models.py
import wave

import os

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from pydub import AudioSegment

from webapp.utils import build_config


def validate_wav(value):
    if not value.name.endswith(('.wav', '.mp3')):
        raise ValidationError('Неверный формат файла')


class WAVFile(models.Model):
    file = models.FileField(upload_to='.', validators=[validate_wav])
    number = models.CharField(verbose_name='DID номер', max_length=50)
    active = models.BooleanField(default=True)

    def __init__(self, *args, **kwargs):
        super(WAVFile, self).__init__(*args, **kwargs)
        self.old_file = self.file

    def convert(self):
        if self.file.name.endswith('.mp3'):
            sound = AudioSegment.from_mp3(self.file.file)
            self.file = self.file.name.replace('.mp3', '.wav')
            self.save()
        else:
            sound = AudioSegment.from_wav(self.file.path)
        sound = sound.set_channels(1)
        sound = sound.set_frame_rate(8000)
        sound = sound.set_sample_width(2)
        sound.export(self.file.path, format="wav")

    @property
    def filename(self):
        return os.path.basename(self.file.name)


@receiver(post_save, sender=WAVFile)
def save(instance, created, **kwargs):
    build_config(WAVFile.objects.filter(active=True))

    if created:
        return

    if instance.old_file.name != instance.file.name and os.path.exists(instance.file.path):
        os.remove(instance.file.path)


@receiver(post_delete, sender=WAVFile)
def delete(instance, **kwargs):
    build_config(WAVFile.objects.filter(active=True))
    if os.path.exists(instance.file.path):
        os.remove(instance.file.path)

fileloader/webapp/forms.py
from django import forms
from .models import WAVFile


class WAVForm(forms.ModelForm):
    class Meta:
        model = WAVFile
        fields = ['file', 'number']
        widgets = {
            'number': forms.NumberInput()
        }


class WAVChangeForm(forms.ModelForm):
    class Meta:
        model = WAVFile
        fields = ['file', 'number', 'active']

fileloader/webapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import wave

from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from webapp.forms import WAVForm, WAVChangeForm
from webapp.models import WAVFile


def wav_add_view(request):
    form = WAVForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save()
        try:
            if wave.open(obj.file.path).getparams()[:3] != (1, 2, 8000):
                raise wave.Error()
        except (FileNotFoundError, wave.Error):
            obj.convert()

        return redirect(reverse('webapp:list'))
    return render(request, 'webapp/wav/add.html', {'form': form})


def wav_list_view(request):
    return render(request, 'webapp/wav/list.html', {'objects': WAVFile.objects.all()})


def wav_change_view(request, pk):
    obj = get_object_or_404(WAVFile, pk=pk)
    form = WAVChangeForm(instance=obj, data=request.POST or None)
    if form.is_valid():
        obj = form.save()
        try:
            if wave.open(obj.file.path).getparams()[:3] != (1, 2, 8000):
                raise wave.Error()
        except (FileNotFoundError, wave.Error):
            obj.convert()
        return redirect(reverse('webapp:list'))
    return render(request, 'webapp/wav/change.html', {'form': form})


def wav_delete_view(request, pk):
    if request.method == 'POST':
        obj = get_object_or_404(WAVFile, pk=pk)
        obj.delete()
        return redirect(reverse('webapp:list'))

    raise Http404()

fileloader/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

fileloader/webapp/templates/webapp/wav/add.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

fileloader/webapp/templates/webapp/wav/change.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

fileloader/webapp/templates/webapp/wav/list.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'webapp:add' %}">Добавить еще</a>
    <div class="list">
        <table border="1" width="80%" style="margin: 0 auto; text-align: center; border-collapse: collapse">
            <thead>
            <tr>
                <th>Файл</th>
                <th>Активный</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for object in objects %}
                <tr>
                    <td width="50%">
                        <p>{{ object.filename }}</p>
                        {% if object.active %}
                        <audio controls style="width: 100%">
                            <source src="{{ object.file.url }}" type="audio/wav">
                        </audio>
                        {% endif %}
                    </td>
                    <td width="20%">{{ object.active|yesno:'Да, Нет' }}</td>
                    <td width="30%">
                        <a href="{% url 'webapp:change' object.id %}">Изменить</a>
                        <form action="{% url 'webapp:delete' object.id %}" method="post">
                            {% csrf_token %}
                            <a class="delete" href="">Удалить</a>
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">Нет данных</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        $('.delete').click(function (e) {
            e.preventDefault();
            if (confirm('Вы действительно хотите удалить файл? ')) {
                $(this).closest('form').submit()
            }
        })
    </script>
{% endblock %}